### ISSUE TITLE
autoupdate() fails due to "pkg_resources" not being available

### ISSUE THREAD

**Issue by pat-s** [lorenzwalthert/precommit#82]
On my HPC I successfully installed pre-commit and linked the executable.
However, when running `precommit::autoupdate()` I get

```r
precommit::autoupdate()
Traceback (most recent call last):
  File "/opt/spack/opt/spack/linux-centos7-x86_64/gcc-9.2.0/py-pre-commit-1.20.0-ib4ogqnt3wwjan5pj6z6ud2ibz2ywh5e/bin/pre-commit", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
Error: Running precommit autoupdate failed.
Call `rlang::last_error()` to see a backtrace
```

Any idea what python dep might be missing and how I can resolve this? I can also ask/look upstream if you say this is out of scope as it is related to a proper install of pre-commit and not the R package :)

**Comment by lorenzwalthert** [comment]
How did you install and what version of python is there? Seems like it could be a problem with setup tools: 
https://github.com/Homebrew/homebrew-core/issues/3078

**Comment by pat-s** [comment]
Via https://spack.io/, a HPC pkg manager.

python 3.7.4

Not on macOS but on CentOS. Spack is os-agnostic though. 


After installing it with pip (python 2.7), the pre-commit exec is in .local/bin. With this I get a different error unfortunately... :/

Continuing tomorrow..

```r
> precommit::autoupdate()
Traceback (most recent call last):
  File "/home/patrick/.local/bin/pre-commit", line 7, in <module>
    from pre_commit.main import main
  File "/home/patrick/.local/lib/python2.7/site-packages/pre_commit/main.py", line 8, in <module>
    import pre_commit.constants as C
  File "/home/patrick/.local/lib/python2.7/site-packages/pre_commit/constants.py", line 7, in <module>
    import importlib_metadata
  File "/home/patrick/.local/lib/python2.7/site-packages/importlib_metadata/__init__.py", line 9, in <module>
    import zipp
  File "/home/patrick/.local/lib/python2.7/site-packages/zipp.py", line 12, in <module>
    import more_itertools
  File "/home/patrick/.local/lib/python2.7/site-packages/more_itertools/__init__.py", line 1, in <module>
    from .more import *  # noqa
  File "/home/patrick/.local/lib/python2.7/site-packages/more_itertools/more.py", line 460
    yield from iterable
             ^
SyntaxError: invalid syntax
Error: Running precommit autoupdate failed.
Call `rlang::last_error()` to see a backtrace.
```

**Comment by michaelquinn32** [comment]
Hi Pat!

It looks like you're trying to run the binary referencing the python3 version of pre-commit but in python 2. Is it still possible that both versions are installed at that machine?

**Comment by pat-s** [comment]
The binary I am referencing was installed using pip via python2. So it should be the python2 version of pre-commit, no?

Yes, the machine runs a Centos7 with both python2 and 3.

**Comment by pat-s** [comment]
Did it again using pip3 and now everything works!

So in summary, I still think doing `pip3 install --user pre-commit` is the easiest way to go :)

And then reference the exec as a R option (or maybe via an env var?). I am happy with this but maybe it can be made easier with miniconda and reticulate.
